# Miniproject - Neuroscience: cellular and circuit mechanisms (BIO-482)

- This notebook contains the part 4 of the miniproject - the personal project.

#### Importing libraries

In [2]:
import os
import sys
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression 
import scipy.stats
import matplotlib.pyplot as plt
import seaborn as sns

#### Importing helper functions
 Feel free to check out what these functions do in the corresponding files, `helpers.py` or `utils.py`. 
 - `helpers.py` contains functions to analyze membrane potential recording data
 - `utils.py` contains functions useful for other things e.g. plotting

In [3]:
base_path = os.getcwd()
base_path = base_path.replace('notebooks', 'scripts') # note: if you have notebooks twice in your base_path, this won't work
sys.path.insert(1, base_path)

from helpers import *
from utils import remove_top_right_frame, jitter_scatterplot

# Load and create data
Load previously saved dataframe as `.csv` file:

In [9]:
df_1 = pd.read_csv('df_1_free.csv')
df_1.head(5)

,Unnamed: 0,cell_id,cell_type,firing_rate,ap_threshold,ap_duration,mean_vm,std_vm,fft_low,fft_high
0,0,AP032_1,PV,0.875000,-0.040795,0.608929,-0.064378,0.005948,0.000763,0.000070
1,1,AP032_2,PV,1.857143,-0.040812,0.993269,-0.056189,0.005208,0.000635,0.000090
2,2,AP035_1,PV,2.100000,-0.037562,0.786111,-0.058273,0.006374,0.000775,0.000053
3,3,AP035_2,PV,0.900000,-0.031695,0.849537,-0.055222,0.006061,0.000837,0.000069
4,4,AP039_1,SST,0.566667,-0.040215,0.866176,-0.060517,0.004220,0.000513,0.000054

In [10]:
df_2 = pd.read_csv('df_2_free.csv')
df_2.head(5)

,Unnamed: 0,cell_id,cell_type,numb_events,wp_avg,wp_amplitude_pre,wp_amplitude_post,vm_avg,vm_amplitude_pre,vm_amplitude_post,ap_avg,ap_psth,ap_fr_pre,ap_fr_post
0,0,AP032_1,PV,17,[-139.34721176 -139.41210588 -139.50944706 -13...,-139.536777,-135.226516,[-0.05683997 -0.05685285 -0.0568672 ... -0.05...,-55.504155,-55.399560,[0. 0. 0. ... 0. 0. 0.],[27.05882353 22.35294118 18.82352941 24.705882...,23.241104,27.065590
1,1,AP032_2,PV,4,[-139.157625 -139.319675 -139.157625 -139.1576...,-139.157622,-134.807553,[-0.0507625 -0.05074375 -0.05072891 ... -0.04...,-48.994021,-50.584425,[0. 0. 0. ... 0. 0. 0.],[35. 15. 45. 25. 25. 15. 15. 5. 15. 15. 20. ...,30.007502,8.752188
2,2,AP035_1,PV,8,[-131.4792875 -131.5651625 -131.3075125 -131.3...,-131.406960,-125.811327,[-0.05370352 -0.05371172 -0.05371602 ... -0.05...,-54.334653,-59.056842,[0. 0. 0. ... 0. 0. 0.],[27.5 20. 17.5 32.5 32.5 15. 2.5 10. 12.5 ...,24.381095,7.501875
3,3,AP035_2,PV,12,[-132.84859167 -132.95124167 -132.95124167 -13...,-132.794568,-118.696745,[-0.04830807 -0.0483013 -0.04829063 ... -0.05...,-50.060496,-53.241710,[0. 0. 0. ... 0. 0. 0.],[48.33333333 41.66666667 26.66666667 40. ...,39.176461,19.588230
4,4,AP039_1,SST,3,[-146.97086667 -146.97086667 -146.97086667 -14...,-146.466663,-138.432118,[-0.05776979 -0.05775417 -0.05775521 ... -0.06...,-57.928339,-62.284089,[0. 0. 0. ... 0. 0. 0.],[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,0.000000,0.000000

In [23]:
df = df_1.merge(df_2, on=['cell_id', 'cell_type'])
df = df.drop(['Unnamed: 0_x'], axis=1)
df.head(5)

,cell_id,cell_type,firing_rate,ap_threshold,ap_duration,mean_vm,std_vm,fft_low,fft_high,Unnamed: 0_y,...,wp_avg,wp_amplitude_pre,wp_amplitude_post,vm_avg,vm_amplitude_pre,vm_amplitude_post,ap_avg,ap_psth,ap_fr_pre,ap_fr_post
0,AP032_1,PV,0.875000,-0.040795,0.608929,-0.064378,0.005948,0.000763,0.000070,0,...,[-139.34721176 -139.41210588 -139.50944706 -13...,-139.536777,-135.226516,[-0.05683997 -0.05685285 -0.0568672 ... -0.05...,-55.504155,-55.399560,[0. 0. 0. ... 0. 0. 0.],[27.05882353 22.35294118 18.82352941 24.705882...,23.241104,27.065590
1,AP032_2,PV,1.857143,-0.040812,0.993269,-0.056189,0.005208,0.000635,0.000090,1,...,[-139.157625 -139.319675 -139.157625 -139.1576...,-139.157622,-134.807553,[-0.0507625 -0.05074375 -0.05072891 ... -0.04...,-48.994021,-50.584425,[0. 0. 0. ... 0. 0. 0.],[35. 15. 45. 25. 25. 15. 15. 5. 15. 15. 20. ...,30.007502,8.752188
2,AP035_1,PV,2.100000,-0.037562,0.786111,-0.058273,0.006374,0.000775,0.000053,2,...,[-131.4792875 -131.5651625 -131.3075125 -131.3...,-131.406960,-125.811327,[-0.05370352 -0.05371172 -0.05371602 ... -0.05...,-54.334653,-59.056842,[0. 0. 0. ... 0. 0. 0.],[27.5 20. 17.5 32.5 32.5 15. 2.5 10. 12.5 ...,24.381095,7.501875
3,AP035_2,PV,0.900000,-0.031695,0.849537,-0.055222,0.006061,0.000837,0.000069,3,...,[-132.84859167 -132.95124167 -132.95124167 -13...,-132.794568,-118.696745,[-0.04830807 -0.0483013 -0.04829063 ... -0.05...,-50.060496,-53.241710,[0. 0. 0. ... 0. 0. 0.],[48.33333333 41.66666667 26.66666667 40. ...,39.176461,19.588230
4,AP039_1,SST,0.566667,-0.040215,0.866176,-0.060517,0.004220,0.000513,0.000054,4,...,[-146.97086667 -146.97086667 -146.97086667 -14...,-146.466663,-138.432118,[-0.05776979 -0.05775417 -0.05775521 ... -0.06...,-57.928339,-62.284089,[0. 0. 0. ... 0. 0. 0.],[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,0.000000,0.000000

In [15]:
print(df_1.shape)
print(df_2.shape)
print(df.shape)

(232, 10)
(232, 14)
(232, 22)

# Part 2 - Membrane potential dynamics and motor activity [2/10 marks]